kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: pwned-python-api-backend-dev
spec:
  replicas: 1
  template:
    metadata:
      name: backend
      labels:
        app: pwned-python-api
        role: backend
        env: dev
    spec:
      containers:
      - name: backend
        image: DOCKER_IMAGE
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        ports:
        - name: backend
          containerPort: 8080
        env:
          - name: FIREBASE
            value: "http://firebase-sync:8080"
        volumeMounts:
          - name: images-store
            mountPath: /app/downloads
    volumes:
      - name: images-store
        persistentVolumeClaim:
          claimName: shared-images-store