kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: pwned-python-api-backend-dev
spec:
  replicas: 1
  template:
    metadata:
      name: backend
      labels:
        app: pwned-python-api
        role: backend
        env: dev
    spec:
      containers:
      - name: backend
        image: DOCKER_IMAGE
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        ports:
        - name: backend
          containerPort: 5000